---
version: "3.7"
services:
  control:
    image: "debian:buster-slim"
    command: "id"
  dockerfile_user:
    build:
      context: .
      dockerfile: samples/02_dockerfile_user/Dockerfile
  gosu:
    build:
      context: .
      dockerfile: samples/03_gosu/Dockerfile
  add_user:
    build:
      context: .
      dockerfile: samples/04_add_user/Dockerfile
  mount_etc_passwd:
    image: "debian:buster-slim"
    command: "id"
    user: "999:999"
    volumes:
      - "./samples/05_mount_etc_passwd/passwd:/etc/passwd:ro"
      - "./samples/05_mount_etc_passwd/group:/etc/group:ro"
