---
version: "3.7"
services:
  control:
    image: "debian:buster-slim"
    command: "id"
  dockerfile_user:
    build:
      context: .
      dockerfile: samples/02_dockerfile_user/Dockerfile
  gosu:
    build:
      context: .
      dockerfile: samples/03_gosu/Dockerfile
